# Generated by Django 4.1.7 on 2023-06-12 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointment_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
