# Generated by Django 4.1.7 on 2023-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.TextField(default='secret'),
        ),
    ]
