# Generated by Django 4.1.7 on 2023-06-12 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
