# Generated by Django 4.1.7 on 2023-06-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret',
        ),
    ]
