# Generated by Django 4.1.7 on 2023-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
